/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.ml.lightgbm;

public interface lightgbmlibConstants {
  public final static int C_API_DTYPE_FLOAT32 = lightgbmlibJNI.C_API_DTYPE_FLOAT32_get();
  public final static int C_API_DTYPE_FLOAT64 = lightgbmlibJNI.C_API_DTYPE_FLOAT64_get();
  public final static int C_API_DTYPE_INT32 = lightgbmlibJNI.C_API_DTYPE_INT32_get();
  public final static int C_API_DTYPE_INT64 = lightgbmlibJNI.C_API_DTYPE_INT64_get();
  public final static int C_API_PREDICT_NORMAL = lightgbmlibJNI.C_API_PREDICT_NORMAL_get();
  public final static int C_API_PREDICT_RAW_SCORE = lightgbmlibJNI.C_API_PREDICT_RAW_SCORE_get();
  public final static int C_API_PREDICT_LEAF_INDEX = lightgbmlibJNI.C_API_PREDICT_LEAF_INDEX_get();
  public final static int C_API_PREDICT_CONTRIB = lightgbmlibJNI.C_API_PREDICT_CONTRIB_get();
  public final static int C_API_MATRIX_TYPE_CSR = lightgbmlibJNI.C_API_MATRIX_TYPE_CSR_get();
  public final static int C_API_MATRIX_TYPE_CSC = lightgbmlibJNI.C_API_MATRIX_TYPE_CSC_get();
  public final static int C_API_FEATURE_IMPORTANCE_SPLIT = lightgbmlibJNI.C_API_FEATURE_IMPORTANCE_SPLIT_get();
  public final static int C_API_FEATURE_IMPORTANCE_GAIN = lightgbmlibJNI.C_API_FEATURE_IMPORTANCE_GAIN_get();
}
