package com.microsoft.ml.lightgbm;

/**
 * Hand-written helper (NOT generated by SWIG, do not delete when regenerating bindings).
 * SWIG generates {@code getCPtr} as {@code protected}, so the raw pointer is only reachable
 * from inside this package. The high-level API needs it to read raw buffers returned by LightGBM.
 */
public final class SwigPointers {
    private SwigPointers() {}

    public static long of(SWIGTYPE_p_void ptr) {
        return SWIGTYPE_p_void.getCPtr(ptr);
    }
}
